### PR TITLE
frontend fixes and smart contract improvements

### PR DESCRIPTION
**Pull request by FarzeenKist**
## Fixes and Improvements

1.  Optimized gas costs throughout your smart contract,(mostly using a storage pointer called CurrentCar).
2. Added check for the new image when calling the upgradeCar function to prevent an empty image URL
3. some typos fix on the smart contract (Cars > cars) and the frontend when you were calling the addHouse instead of addCar
4. I've added the mapping carIdentifier to prevent two cars with the same registration plate number to be added to the platform at the same time as this could cause logistic issues/spam.
5.  Removed the need to approve the car price when upgrading a car on the frontend as this could lead to a security vulnerability and is also redundant
6. Finally, I've also added the functionality to remove a car from the platform

### CODE REVIEW

**Comment by DavidIfebueme** [comment]
Hello @Farzeen,

After incorporating the changes advised and rehosting the marketplace on GitHub pages, the buyCar function on the contract does not work anymore.
I have been trying to fix this for a while now. Can please you take a look at it?

**Comment by FarzeenKist** [comment]
Hello @DavidIfebueme , did you redeploy the smart contract and replaced the old smart contract address with the new one? As a side note, you only need to update the ABI

**Comment by FarzeenKist** [comment]
Can you also add this line in the buyCar function(after currentCar.owner is reassigned to caller):
`currentCar.sold = true;` (seems I forgot to do that in my PR, sorry about that)

**Comment by DavidIfebueme** [comment]
Thanks @FarzeenKist.

That fixed it. I also added registrationPlate function to the DAPP frontend.

**Pull request merged**
